### ISSUE TITLE
Test IGDB

### ISSUE THREAD

**Issue by NerdyStuff** [Grimmig18/find-a-gamer#15]
https://api.igdb.com/

**Comment by NerdyStuff** [comment]
https://api-docs.igdb.com/#about

**Comment by Grimmig18** [comment]
Struktur einer Anfrage in Plain Text:
`POST /games HTTP/1.1
Host: api-v3.igdb.com
user-key: <user-key>
Content-Type: text/plain
Content-Length: 120

fields name,popularity,version_parent; 
sort popularity desc; 
limit 100; 
where popularity > 1 & version_parent = null;`
